"""add xml_source_id to marketplace_products

Revision ID: 0e25b0f8d8dc
Revises: 9f8e0d7c4a1b
Create Date: 2026-01-04 16:30:03.027871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e25b0f8d8dc'
down_revision = '9f8e0d7c4a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xml_source_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_marketplace_products_xml_source_id'), ['xml_source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_products_xml_source_id'))
        batch_op.drop_column('xml_source_id')

    # ### end Alembic commands ###
