"""add missing columns to supplier_xmls

Revision ID: 11736efe5e8f
Revises: bcd464bb88ed
Create Date: 2026-01-03 14:04:56.904112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11736efe5e8f'
down_revision = 'bcd464bb88ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_xmls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_random_barcode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_cached_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sync_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sync_logs_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sync_logs_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sync_logs_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('supplier_xmls', schema=None) as batch_op:
        batch_op.drop_column('last_cached_at')
        batch_op.drop_column('use_random_barcode')

    # ### end Alembic commands ###
