"""Add CachedXmlProduct and PersistentJob models

Revision ID: 6b95315f3776
Revises: 0e25b0f8d8dc
Create Date: 2026-01-04 21:10:34.287724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b95315f3776'
down_revision = '0e25b0f8d8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('marketplace_products', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_marketplace_products_xml_source_id'), ['xml_source_id'], unique=False)

    op.create_table('cached_xml_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xml_source_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stock_code', sa.String(length=200), nullable=False),
    sa.Column('barcode', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=500), nullable=True),
    sa.Column('images_json', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['xml_source_id'], ['supplier_xmls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cached_xml_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_xml_products_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_cached_xml_products_stock_code'), ['stock_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_cached_xml_products_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cached_xml_products_xml_source_id'), ['xml_source_id'], unique=False)
        batch_op.create_index('idx_xml_stock_code', ['xml_source_id', 'stock_code'], unique=False)

    op.create_table('persistent_jobs',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('marketplace', sa.String(length=50), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.Column('logs_json', sa.Text(), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persistent_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persistent_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_persistent_jobs_marketplace'), ['marketplace'], unique=False)
        batch_op.create_index(batch_op.f('ix_persistent_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_persistent_jobs_user_id'), ['user_id'], unique=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persistent_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persistent_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_persistent_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_persistent_jobs_marketplace'))
        batch_op.drop_index(batch_op.f('ix_persistent_jobs_job_type'))

    op.drop_table('persistent_jobs')
    with op.batch_alter_table('cached_xml_products', schema=None) as batch_op:
        batch_op.drop_index('idx_xml_stock_code')
        batch_op.drop_index(batch_op.f('ix_cached_xml_products_xml_source_id'))
        batch_op.drop_index(batch_op.f('ix_cached_xml_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_cached_xml_products_stock_code'))
        batch_op.drop_index(batch_op.f('ix_cached_xml_products_barcode'))

    op.drop_table('cached_xml_products')
    # with op.batch_alter_table('marketplace_products', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_marketplace_products_xml_source_id'))


    # ### end Alembic commands ###
