"""add is_support to users

Revision ID: 9f8e0d7c4a1b
Revises: 11736efe5e8f
Create Date: 2026-01-04 12:46:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8e0d7c4a1b'
down_revision = '11736efe5e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_support', sa.Boolean(), nullable=True, server_default='false'))

    # Update existing rows to have False for is_support
    op.execute("UPDATE users SET is_support = false WHERE is_support IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_support')

    # ### end Alembic commands ###
