"""ilk kurulum ve cargo kodu

Revision ID: bcd464bb88ed
Revises: 
Create Date: 2025-12-14 23:09:54.557832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd464bb88ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto_sync', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auto_sync_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('unique_user_marketplace', ['user_id', 'marketplace'])
        batch_op.create_foreign_key(batch_op.f('fk_auto_sync_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('batch_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_batch_logs_batch_id'), ['batch_id'])
        batch_op.create_foreign_key(batch_op.f('fk_batch_logs_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('brand_mappings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('source_brand',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('marketplace',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('target_brand_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('idx_brand_mapping_source', ['source_brand'], unique=False)
        batch_op.create_unique_constraint('uq_brand_mapping', ['source_brand', 'marketplace'])

    with op.batch_alter_table('category_mappings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('source_category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('marketplace',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('target_category_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('idx_cat_mapping_source', ['source_category'], unique=False)
        batch_op.create_unique_constraint('uq_category_mapping', ['source_category', 'marketplace'])

    with op.batch_alter_table('excel_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excel_files_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_excel_files_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_code', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_orders_marketplace_order_id'))
        batch_op.create_index(batch_op.f('ix_orders_marketplace_order_id'), ['marketplace_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_shipment_package_id'), ['shipment_package_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('unique_user_marketplace_order', ['user_id', 'marketplace_order_id'])
        batch_op.create_foreign_key(batch_op.f('fk_orders_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('cost_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.drop_index(batch_op.f('idx_products_barcode'))
        batch_op.drop_index(batch_op.f('idx_products_title'))
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('unique_user_barcode', ['user_id', 'barcode'])
        batch_op.create_foreign_key(batch_op.f('fk_products_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('unique_user_key', ['user_id', 'key'])
        batch_op.create_foreign_key(batch_op.f('fk_settings_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_subscriptions_user_id'), ['user_id'])

    with op.batch_alter_table('supplier_xmls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_xmls_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_supplier_xmls_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_xmls', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_supplier_xmls_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_supplier_xmls_user_id'))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subscriptions_user_id'), type_='unique')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_settings_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint('unique_user_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_settings_user_id'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_products_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint('unique_user_barcode', type_='unique')
        batch_op.drop_index(batch_op.f('ix_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))
        batch_op.create_index(batch_op.f('idx_products_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('idx_products_barcode'), ['barcode'], unique=False)
        batch_op.alter_column('cost_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint('unique_user_marketplace_order', type_='unique')
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_shipment_package_id'))
        batch_op.drop_index(batch_op.f('ix_orders_marketplace_order_id'))
        batch_op.create_index(batch_op.f('ix_orders_marketplace_order_id'), ['marketplace_order_id'], unique=1)
        batch_op.drop_column('cargo_code')

    with op.batch_alter_table('excel_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_excel_files_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_excel_files_user_id'))

    with op.batch_alter_table('category_mappings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_mapping', type_='unique')
        batch_op.drop_index('idx_cat_mapping_source')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('target_category_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('marketplace',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('source_category',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('brand_mappings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_brand_mapping', type_='unique')
        batch_op.drop_index('idx_brand_mapping_source')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('target_brand_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('marketplace',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('source_brand',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('batch_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_batch_logs_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_batch_logs_batch_id'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_batch_logs_user_id'))

    with op.batch_alter_table('auto_sync', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_auto_sync_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint('unique_user_marketplace', type_='unique')
        batch_op.drop_index(batch_op.f('ix_auto_sync_user_id'))

    # ### end Alembic commands ###
